name: Reinventory Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * *"  # 13:00 UTC ~= 9:00 America/New_York most of the year

env:
  TZ: America/New_York
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Step 1 — Fetch all Clover inventory
        env:
          CLOVER_API_TOKEN: ${{ secrets.CLOVER_API_TOKEN }}
          CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
        run: |
          python getAllInvItems.py
        # expected output: clover_items.xlsx

      - name: Step 2 — Fetch 3 months of sales (orders)
        env:
          CLOVER_API_TOKEN: ${{ secrets.CLOVER_API_TOKEN }}
          CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
        run: |
          python getOrdersForL3Mos.py
        # expected output: product_names_last_3_months.xlsx

      - name: Step 3 — Map inventory to sold items (unique products)
        run: |
          python mapItems.py
        # expected output: mapped_items.xlsx

      - name: Step 4 — Build final XLSX + dated CSV
        run: |
          python final_file.py
        # expected outputs:
        # - processed_new_inventory_final.xlsx
        # - <YYYYMMDD>_store_reinventory.csv

      - name: Upload outputs (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: reinventory_outputs
          path: |
            clover_items.xlsx
            product_names_last_3_months.xlsx
            mapped_items.xlsx
            processed_new_inventory_final.xlsx
            *_store_reinventory.csv
          if-no-files-found: warn

