name: Reinventory Pipeline

on:
  workflow_dispatch: {}

env:
  TZ: America/New_York
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 1: Fetch all Clover inventory -> clover_items.xlsx
      - name: Fetch all Clover inventory
        env:
          CLOVER_API_TOKEN: ${{ secrets.CLOVER_API_TOKEN }}
          CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
        run: |
          python scripts/getAllInvItems.py

      # Step 2: Fetch 3 months of sales -> product_names_last_3_months.xlsx
      - name: Fetch last 3 months of sales
        env:
          CLOVER_API_TOKEN: ${{ secrets.CLOVER_API_TOKEN }}
          CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
        run: |
          python scripts/getOrdersForL3Mos.py

      # Step 3: Map inventory to sold items -> mapped_items.xlsx
      - name: Map inventory to sold items
        run: |
          python scripts/mapItems.py

      # Step 4: Build final XLSX + dated CSV
      - name: Build final outputs
        run: |
          python scripts/final_file.py

      # Upload everything useful
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reinventory_outputs
          path: |
            clover_items.xlsx
            product_names_last_3_months.xlsx
            mapped_items.xlsx
            processed_new_inventory_final.xlsx
            *_store_reinventory.csv
          if-no-files-found: warn

